base:
  project: simple_wine_app
  random_state: 7
  target_col: TARGET

data_source:
  s3_source: data\raw\winequality.csv

load_data:
  raw_dataset_csv: data\interim\winequality.csv

split_data:
  train_path: data\processed\train_winequality.csv
  test_path: data\processed\test_winequality.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.8
      l1_ratio: 0.69
model_dir: saved_models

reports:
  params: reports/params.json
  scores: reports/scores.json

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: ElasticNet regression
  run_name: mlops
  registered_model_name: ElasticModel
  remote_server_uri: http://192.168.0.235:8501
  